# Generated by Django 3.1.7 on 2021-04-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataproject',
            name='TimeAdd',
        ),
    ]
